-- 코드를 작성해주세요
SELECT ID, COUNT(CHILD_ID) AS CHILD_COUNT
FROM (
    SELECT A.ID, B.ID AS CHILD_ID
    FROM ECOLI_DATA A LEFT OUTER JOIN ECOLI_DATA B
    ON A.ID = B.PARENT_ID
)C
GROUP BY ID
ORDER BY ID