-- 코드를 입력하세요
SELECT PRODUCT_CODE, (PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT p
INNER JOIN (

    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
)a
ON p.PRODUCT_ID = a.PRODUCT_ID
ORDER BY SALES desc, PRODUCT_CODE