SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, RANK()OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES desc) as rnk
    FROM REST_INFO
)a
WHERE rnk = 1
ORDER BY FOOD_TYPE desc
    