-- 코드를 작성해주세요
SELECT ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') AS TOTAL_DISTANCE, CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
# CONCAT을 해서 더이상 TOTAL_DISTANCE는 숫자가 아님
ORDER BY ROUND(SUM(D_BETWEEN_DIST),1) desc