-- 코드를 입력하세요
SELECT HISTORY_ID,
CASE
    WHEN a.DURATION_TYPE = 'None' THEN DAILY_FEE * DATES
    ELSE ROUND(DAILY_FEE * DATES * (100-DISCOUNT_RATE) / 100, 0)
END AS FEE
FROM (
    SELECT HISTORY_ID,
    CASE
        WHEN DATES >= 7 and DATES < 30 THEN '7일 이상'
        WHEN DATES >= 30 and DATES < 90 THEN '30일 이상'
        WHEN DATES >= 90 THEN '90일 이상'
        ELSE 'None'
    END AS DURATION_TYPE, DAILY_FEE, DATES
    FROM CAR_RENTAL_COMPANY_CAR c
    INNER JOIN (
        SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE)+1 AS DATES
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) h
    ON c.CAR_ID = h.CAR_ID
    WHERE CAR_TYPE = '트럭'
)a LEFT OUTER JOIN (

    SELECT DURATION_TYPE, REPLACE(DISCOUNT_RATE, '%', '') AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'

)p
ON a.DURATION_TYPE = p.DURATION_TYPE
ORDER BY FEE desc, HISTORY_ID desc