-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER u INNER JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
)b
ON b.WRITER_ID = u.USER_ID
ORDER BY TOTAL_SALES