-- 코드를 입력하세요
SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM (
    SELECT ANIMAL_ID, DATETIME, EXTRACT(HOUR FROM DATETIME) AS HOUR
    FROM ANIMAL_OUTS  
) A
GROUP BY HOUR
HAVING HOUR BETWEEN 9 AND 19
ORDER BY HOUR