SELECT E1.YEAR, M - S AS YEAR_DEV, E1.ID
FROM
(
    SELECT ID, SIZE_OF_COLONY AS S, EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
)E1 INNER JOIN 
(
    SELECT YEAR, MAX(SIZE_OF_COLONY) as M
    FROM (
        SELECT ID, EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR, SIZE_OF_COLONY
        FROM ECOLI_DATA
    )A
    GROUP BY YEAR
)E2
ON E1.YEAR = E2.YEAR
ORDER BY YEAR, YEAR_DEV