-- 코드를 작성해주세요
SELECT SUM(FISH_COUNT) AS FISH_COUNT
FROM (
    SELECT FISH_TYPE, COUNT(*) AS FISH_COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)A INNER JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER'