SELECT ID, FISH_NAME, LENGTH
FROM FISH_NAME_INFO b INNER JOIN (
    SELECT ID, i.FISH_TYPE, a.LENGTH AS LENGTH
    FROM FISH_INFO i INNER JOIN (
        SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    )a
    ON i.FISH_TYPE = a.FISH_TYPE
    WHERE i.LENGTH = a.LENGTH
)c
ON b.FISH_TYPE = c.FISH_TYPE
ORDER BY ID