-- 코드를 작성해주세요
SELECT e.DEPT_ID, DEPT_NAME_EN, ROUND(AVG_SAL,0) AS AVG_SAL
FROM HR_DEPARTMENT d INNER JOIN (
    SELECT DEPT_ID, AVG(SAL) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)e
ON d.DEPT_ID = e.DEPT_ID
ORDER BY AVG_SAL desc