-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK b
INNER JOIN
(
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
)s
ON b.BOOK_ID = s.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY